#!/usr/bin/env bash
set -euo pipefail

resolution=${VNC_RESOLUTION:-1280x900}
depth=${VNC_DEPTH:-24}
exec /usr/bin/Xvfb "${DISPLAY:-:1}" -screen 0 "${resolution}x${depth}" -nolisten tcp +extension GLX +render -noreset
